name: music_app
description: A music application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.1
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  cloud_firestore: ^4.0.5
  google_sign_in: ^5.4.2
  fpdart: ^0.3.0
  equatable: ^2.0.5
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0


  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
